Removed Prettier and added Biome
ronin-co/react-attention pull request #1
Opened 2024-09-18 08:50 UTC by colodenn

Removed Prettier from the repository and replaced it with Biome. Biome provides excellent linting and analysis capabilities.

2024-09-18 09:21 UTC, NuroDev commented on src/hook.tsx
> +  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation>
Can we add an actual explanation here

2024-09-24 08:14 UTC, leo requested changes

2024-09-24 08:14 UTC, leo commented on src/hook.tsx
> +    useEffect(() => {
This is incorrect. Can you run `bun run format` please, and copy the script from our other repos?

2024-09-24 08:14 UTC, leo commented on package.json
>      "prettier": "3.2.4",
Why is `prettier` still in the list of dependencies?

2024-09-24 08:34 UTC, leo approved these changes

2024-09-25 08:57 UTC, merged